const { app, BrowserWindow, ipcMain, safeStorage, session } = require('electron');
const https=require('https');const path=require('path');const fs=require('fs');
let mainWindow;const dataDir=path.join(app.getPath('userData'),'secure-data');const authFile=path.join(dataDir,'auth.json');const recordsFile=path.join(dataDir,'records.enc');
function httpsJson(url,timeoutMs=7000){return new Promise((resolve,reject)=>{const req=https.get(url,{headers:{'User-Agent':'BTC-15M-Controller/5.0'}},res=>{let d='';res.on('data',c=>d+=c);res.on('end',()=>{if(res.statusCode<200||res.statusCode>=300)return reject(new Error(`HTTP ${res.statusCode}`));try{resolve(JSON.parse(d))}catch(e){reject(e)}})});req.setTimeout(timeoutMs,()=>req.destroy(new Error('Request timed out')));req.on('error',reject)})}
function ensureDataDir(){fs.mkdirSync(dataDir,{recursive:true})}
function createWindow(){mainWindow=new BrowserWindow({width:1500,height:1050,minWidth:1150,minHeight:800,title:'BTC 15-Minute Controller — Strategy Engine',webPreferences:{preload:path.join(__dirname,'preload.js'),nodeIntegration:false,contextIsolation:true,sandbox:true,devTools:false}});mainWindow.setMenuBarVisibility(false);mainWindow.loadFile(path.join(__dirname,'index.html'));mainWindow.webContents.on('will-navigate',e=>e.preventDefault());mainWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}))}
app.whenReady().then(()=>{ensureDataDir();session.defaultSession.webRequest.onHeadersReceived((d,cb)=>cb({responseHeaders:{...d.responseHeaders,'Content-Security-Policy':["default-src 'self'; connect-src 'self' https://api.elections.kalshi.com https://api.kalshi.com; img-src 'self' data:; style-src 'self'; script-src 'self'"]}}));
ipcMain.handle('kalshi:status',()=>({mode:'PUBLIC_MARKET_DATA',tradingEnabled:false,credentialStored:false}));
ipcMain.handle('kalshi:markets',async(_e,p={})=>{const limit=Math.min(Number(p.limit)||100,1000);const u=new URL('https://api.elections.kalshi.com/trade-api/v2/markets');u.searchParams.set('limit',String(limit));if(p.status)u.searchParams.set('status',String(p.status));if(p.cursor)u.searchParams.set('cursor',String(p.cursor));return await httpsJson(u.toString())});
ipcMain.handle('kalshi:market',async(_e,t)=>{if(typeof t!=='string'||!t)throw new Error('Missing market ticker');return await httpsJson(`https://api.elections.kalshi.com/trade-api/v2/markets/${encodeURIComponent(t)}`)});
ipcMain.handle('kalshi:snapshot',async(_e,t)=>{if(typeof t!=='string'||!t)throw new Error('Missing market ticker');const s=encodeURIComponent(t);const [mr,br]=await Promise.all([httpsJson(`https://api.elections.kalshi.com/trade-api/v2/markets/${s}`),httpsJson(`https://api.elections.kalshi.com/trade-api/v2/markets/${s}/orderbook`)]);const m=mr.market||mr,b=br.orderbook||br;const pick=(...xs)=>{for(const x of xs){const n=Number(x);if(Number.isFinite(n))return n}return null};
 const yesBid=pick(m.yes_bid,m.yes_bid_dollars),yesAsk=pick(m.yes_ask,m.yes_ask_dollars),noBid=pick(m.no_bid,m.no_bid_dollars),noAsk=pick(m.no_ask,m.no_ask_dollars),last=pick(m.last_price,m.last_price_dollars);
 return {ticker:m.ticker,eventTicker:m.event_ticker,seriesTicker:m.series_ticker,title:m.title,subtitle:m.subtitle,status:m.status,closeTime:m.close_time,openTime:m.open_time,expirationTime:m.expiration_time,result:m.result,yesBid,yesAsk,noBid,noAsk,lastPrice:last,orderbook:{yes:Array.isArray(b?.yes)?b.yes:[],no:Array.isArray(b?.no)?b.no:[]},strike:m.floor_strike??m.strike??null,raw:{...m}};
});
ipcMain.handle('kalshi:orderbook',async(_e,t)=>{if(typeof t!=='string'||!t)throw new Error('Missing market ticker');return await httpsJson(`https://api.elections.kalshi.com/trade-api/v2/markets/${encodeURIComponent(t)}/orderbook`)});
ipcMain.handle('auth:status',()=>({configured:fs.existsSync(authFile),safeStorageAvailable:safeStorage.isEncryptionAvailable()}));
ipcMain.handle('auth:set-passcode',async(_e,p)=>{try{if(typeof p!=='string'||p.length<12)throw new Error('Passcode must be at least 12 characters.');if(!safeStorage.isEncryptionAvailable())throw new Error('OS secure storage unavailable.');ensureDataDir();const verifier=safeStorage.encryptString(p).toString('base64');fs.writeFileSync(authFile,JSON.stringify({verifier}),{mode:0o600});return true}catch(e){console.error('auth:set-passcode failed:',e);return false}});
ipcMain.handle('auth:verify',async(_e,p)=>{try{const o=JSON.parse(fs.readFileSync(authFile,'utf8'));return safeStorage.decryptString(Buffer.from(o.verifier,'base64'))===p}catch{return false}});
ipcMain.handle('records:read',()=>{if(!fs.existsSync(recordsFile))return [];try{return JSON.parse(safeStorage.decryptString(fs.readFileSync(recordsFile)))}catch{return []}});
ipcMain.handle('records:write',(_e,r)=>{if(!safeStorage.isEncryptionAvailable())throw new Error('OS secure storage unavailable.');fs.writeFileSync(recordsFile,safeStorage.encryptString(JSON.stringify(Array.isArray(r)?r:[])),{mode:0o600});return true});createWindow()});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
