const $=id=>document.getElementById(id);let market=null,btc=null,lastProb=null,lastAlertKey='',lead=3,topic=localStorage.getItem('btc15_topic')||'',timer=null;let lastTick=Date.now();$('topic').value=topic;
const money=n=>Number.isFinite(n)?'$'+n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
const pct=n=>Number.isFinite(n)?n.toFixed(1)+'%':'—';
function addAlert(msg,type='info',key=''){if(key&&key===lastAlertKey)return;lastAlertKey=key;const box=$('alerts');const e=document.createElement('div');e.className='alert-item '+type;e.innerHTML='<time>'+new Date().toLocaleTimeString()+'</time>'+msg;const empty=box.querySelector('.empty');if(empty)empty.remove();box.prepend(e);while(box.children.length>8)box.lastChild.remove();notifyExternal(msg,type);}
async function notifyExternal(msg,type){if(topic){try{await fetch('https://ntfy.sh/'+encodeURIComponent(topic),{method:'POST',headers:{Title:'BTC 15-Minute Controller',Priority:type==='danger'?'urgent':type==='good'?'default':'high',Tags:type==='danger'?'warning':type==='good'?'chart_with_upwards_trend':'bell'},body:msg})}catch{}}if('Notification'in window&&Notification.permission==='granted'){try{new Notification('BTC 15-Minute Controller',{body:msg,tag:'btc15m'})}catch{}}}
async function requestNotify(){if(!('Notification'in window)){alert('This browser does not support notifications.');return}const p=await Notification.requestPermission();$('notify').textContent=p==='granted'?'PHONE ALERTS: ON':'ENABLE PHONE ALERTS';if(p==='granted')addAlert('Phone alerts enabled.','good','notify-on')}
async function fetchJSON(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
async function refreshBTC(){try{const [c,k]=await Promise.allSettled([fetchJSON('https://api.coinbase.com/v2/prices/BTC-USD/spot'),fetchJSON('https://api.kraken.com/0/public/Ticker?pair=XBTUSD')]);const a=[];if(c.status==='fulfilled')a.push(Number(c.value?.data?.amount));if(k.status==='fulfilled'){const key=Object.keys(k.value?.result||{})[0];a.push(Number(k.value?.result?.[key]?.c?.[0]))}const p=a.filter(Number.isFinite).sort((x,y)=>x-y);btc=p.length?(p.length%2?p[(p.length-1)/2]:(p[p.length/2-1]+p[p.length/2])/2):null;if(btc!==null)$('btc').textContent=money(btc)}catch{}}
function targetOf(m){for(const x of [m?.floor_strike,m?.strike,m?.floor_strike_dollars]){const n=Number(x);if(Number.isFinite(n)&&n>1000)return n}const title=String(m?.title||'');const x=title.match(/\$?([0-9]{5}(?:\.[0-9]+)?)/);return x?Number(x[1]):null}
function probOf(m){let y=Number(m?.yes_bid_dollars??m?.yes_bid),a=Number(m?.yes_ask_dollars??m?.yes_ask);if(Number.isFinite(y)&&y<=1)y*=100;if(Number.isFinite(a)&&a<=1)a*=100;return Number.isFinite(y)&&Number.isFinite(a)?(y+a)/2:null}
async function refreshMarket(){try{const d=await fetchJSON('https://external-api.kalshi.com/trade-api/v2/markets?limit=100&status=open&series_ticker=KXBTC15M');const ms=d.markets||[];const now=Date.now();const candidates=ms.filter(m=>new Date(m.open_time||0).getTime()<=now&&new Date(m.close_time||m.expiration_time||0).getTime()>now);candidates.sort((a,b)=>new Date(a.close_time).getTime()-new Date(b.close_time).getTime());if(!candidates.length)throw new Error('No active BTC 15M market');market=candidates[0];renderMarket();$('liveDot').textContent='LIVE';$('liveDot').style.color='#7ff2b5'}catch(e){$('liveDot').textContent='RETRYING'}} 
function renderMarket(){if(!market)return;const target=targetOf(market),p=probOf(market),close=new Date(market.close_time||market.expiration_time).getTime(),open=new Date(market.open_time||close-900000).getTime(),remaining=Math.max(0,close-Date.now()),elapsed=Math.max(0,Date.now()-open),mins=Math.floor(remaining/60000),secs=Math.floor((remaining%60000)/1000);const up=p??null,down=p!==null?100-p:null;const pick=p!==null?(p>=52?'UP':p<=48?'DOWN':'WAIT'):'WAIT';const confidence=p!==null?Math.min(94,50+Math.abs(p-50)*1.7):0;const risk=remaining<600?'HIGH':Math.abs((btc||target||0)-(target||btc||0))/(target||1)*100<.15?'LOW':'MEDIUM';$('window').textContent=(Number(market.window_number)||'—')+' / 15';$('target').textContent=money(target);$('pick').textContent=pick;$('confidence').textContent=pct(confidence);$('risk').textContent=risk;$('ticker').textContent=market.ticker||'—';$('closes').textContent=new Date(close).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});$('prob').textContent=(up??'—')+'% / '+(down??'—')+'%';$('countdown').textContent=mins+':'+String(secs).padStart(2,'0');$('progress').style.width=Math.min(100,elapsed/900000*100)+'%';$('score').textContent=(confidence*0.34).toFixed(1);$('spread').textContent='—';$('momentum').textContent=btc&&target?(btc>=target?'UP':'DOWN'):'—';$('signalTitle').textContent=pick==='WAIT'?'WAIT • MARKET NEUTRAL':pick+' • '+confidence.toFixed(0)+'% CONFIDENCE';$('signalText').textContent=pick==='WAIT'?'Kalshi is inside the neutral band; monitoring for a meaningful move.':('BTC is '+(btc>=target?'above':'below')+' target. Kalshi direction is '+pick+'.');checkAlerts(remaining,pick,up);lastProb=up}
function checkAlerts(rem,pick,up){const mins=Math.ceil(rem/60000);if(mins<=lead&&mins>=1)addAlert('Window closes in about '+mins+' minute'+(mins===1?'':'s')+'.',mins===1?'warn':'info','close:'+market.ticker+':'+mins);if(pick!=='WAIT'&&up!==null)addAlert('Meaningful market direction: '+pick+' ('+up.toFixed(1)+'% YES).','good','dir:'+market.ticker+':'+pick+':'+Math.floor(up));if(lastProb!==null&&pick!=='WAIT'&&((lastProb<48&&up>=52)||(lastProb>52&&up<=48)))addAlert('Market reversal detected: '+pick+'.','danger','flip:'+market.ticker+':'+pick)}
function tick(){if(market)renderMarket();if(Date.now()-lastTick>12000){lastTick=Date.now();refreshBTC()}if(!market||Date.now()>=new Date(market.close_time||market.expiration_time).getTime())refreshMarket()}
$('notify').onclick=requestNotify;$('refresh').onclick=()=>refreshMarket();$('lead').onchange=e=>{lead=Number(e.target.value)};$('topic').onchange=e=>{topic=e.target.value.trim();localStorage.setItem('btc15_topic',topic)};$('paper').onclick=e=>{e.target.textContent=e.target.textContent.includes('ON')?'PAPER MODE: ON':'PAPER MODE: ON'};window.addEventListener('load',()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');refreshBTC();refreshMarket();timer=setInterval(tick,1000);setInterval(refreshMarket,15000);if(Notification?.permission==='granted')$('notify').textContent='PHONE ALERTS: ON'});